on:
  push:
jobs:
  cache:
    name: Build and cache nix artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    # yoinked from https://github.com/ifd3f/infra/blob/main/.github/workflows/check-targets.yml
    - name: Remove unneccessary packages
      run: 'echo "=== Before pruning ==="

        df -h

        sudo rm -rf /usr/bin/buildah /usr/bin/containerd* /usr/bin/ctr /usr/bin/docker*
        /usr/bin/gh /usr/bin/git /usr/bin/gpg /usr/bin/grub* /usr/bin/mono-sgen
        /usr/bin/myisam* /usr/bin/mysql* /usr/bin/openssl /usr/bin/pedump /usr/bin/php*
        /usr/bin/podman /usr/bin/python3.10 /usr/bin/shellcheck /usr/bin/skopeo
        /usr/bin/snap /usr/bin/tcpdump /usr/bin/tmux /usr/bin/x86_64-linux-gnu-*
        /usr/bin/yq /opt /usr/local /usr/share /var/lib /var/log || true

        echo

        echo "=== After pruning ==="

        df -h
        '
    - uses: cachix/cachix-action@v12
      with:
        name: ashhhleyyy
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: GC_DONT_GC=1 nix build --show-trace --log-lines 10000 --fallback '.#nixosConfigurations.amy.config.system.build.toplevel'
    - run: df -h
